#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -q --no-repo-verify --depth=1 -u git://github.com/DerpFest-11/manifest.git -b 11 -g default,-device,-mips,-darwin,-notdefault

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

# clone device tree vendor and kernel and remove default hals then clone custom 
find hardware/qcom-caf/msm8996/display hardware/qcom-caf/msm8996/audio hardware/qcom-caf/msm8996/media hardware/qcom-caf/wlan -delete
git clone https://github.com/Erickeagle3/device_xiaomi_mido -b derp device/xiaomi/mido --depth=1
git clone https://github.com/Erickeagle3/vendor_xiaomi -b cr7 vendor/xiaomi --depth=1
git clone https://github.com/zeelog/android_kernel_xiaomi_mido -b lineage-18.1 kernel/xiaomi/mido --depth=1
git clone https://github.com/android-eleven/hardware_qcom_display -b caf-msm8996-r hardware/qcom-caf/msm8996/display --depth=1
git clone https://github.com/android-eleven/hardware_qcom_audio -b caf-msm8996-r hardware/qcom-caf/msm8996/audio --depth=1
git clone https://github.com/android-eleven/hardware_qcom_media -b caf-msm8996-r hardware/qcom-caf/msm8996/media --depth=1
git clone https://android.googlesource.com/platform/hardware/qcom/wlan hardware/qcom-caf/wlan --depth=1
